name: tkdhub-dojo
region: nyc
services:
- name: dojo-api
  image:
    registry: tkdhub-registry
    registry_type: DOCR
    repository: dojo-api
    tag: latest
  instance_count: 1
  instance_size_slug: apps-s-1vcpu-1gb
  http_port: 8080
  health_check:
    http_path: /health
  envs:
  - key: ASPNETCORE_ENVIRONMENT
    scope: RUN_AND_BUILD_TIME
    value: Production
  - key: ConnectionStrings__DojoDatabase
    scope: RUN_AND_BUILD_TIME
    type: SECRET
  - key: JwtSettings__Issuer
    scope: RUN_AND_BUILD_TIME
    value: IdentityAPI-Prod
  - key: JwtSettings__Audience
    scope: RUN_AND_BUILD_TIME
    value: MicroservicesUsers-Prod
  - key: JwtSettings__ExpiryMinutes
    scope: RUN_AND_BUILD_TIME
    value: "60"
  - key: RestKeySettings__Key
    scope: RUN_AND_BUILD_TIME
    type: SECRET
  - key: RestKeySettings__HeaderName
    scope: RUN_AND_BUILD_TIME
    value: X-Rest-Key
  - key: IdentityApiSettings__BaseUrl
    scope: RUN_AND_BUILD_TIME
    value: "https://tkdhub-identity-n3lku.ondigitalocean.app"
  - key: ErrorLogSettings__BaseUrl
    scope: RUN_AND_BUILD_TIME
    value: "https://tkdhub-identity-n3lku.ondigitalocean.app"
  - key: ErrorLogSettings__ServiceKey
    scope: RUN_AND_BUILD_TIME
    type: SECRET
  - key: JwtSettings__Secret
    scope: RUN_AND_BUILD_TIME
    type: SECRET
  - key: CloudinarySettings__CloudName
    scope: RUN_AND_BUILD_TIME
    value: "dlrjvaexg"
  - key: CloudinarySettings__ApiKey
    scope: RUN_AND_BUILD_TIME
    value: "318563189243923"
  - key: CloudinarySettings__ApiSecret
    scope: RUN_AND_BUILD_TIME
    type: SECRET
ingress:
  rules:
  - component:
      name: dojo-api
    match:
      path:
        prefix: /
