name: tkdhub-identity
region: nyc

services:
  - name: identity-api
    image:
      registry_type: DOCR
      registry: tkdhub-registry
      repository: identity-api
      tag: latest
    http_port: 8080
    instance_count: 1
    instance_size_slug: apps-s-1vcpu-0.5gb
    health_check:
      http_path: /health
    envs:
      - key: ASPNETCORE_ENVIRONMENT
        value: Production
