using Identity.API.Filters;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Shared.Application.Models;
using Shared.Domain.Entities;
using Shared.Domain.Repositories;

namespace Identity.API.Controllers
{
    [ApiController]
    [Route("api/[controller]")]
    public class ErrorLogsController : ControllerBase
    {
        private readonly IErrorLogRepository _errorLogRepository;

        public ErrorLogsController(IErrorLogRepository errorLogRepository)
        {
            _errorLogRepository = errorLogRepository;
        }

        /// <summary>
        /// Receives an error log from any downstream service and persists it centrally.
        /// Authenticated via the shared <c>X-Rest-Key</c> header (service-to-service).
        /// </summary>
        [HttpPost]
        [AllowAnonymous]
        [RequireRestKey]
        [ProducesResponseType(StatusCodes.Status204NoContent)]
        [ProducesResponseType(StatusCodes.Status401Unauthorized)]
        public async Task<IActionResult> CreateErrorLog(
            [FromBody] ErrorLogPayload payload,
            CancellationToken cancellationToken = default)
        {
            var errorLog = ErrorLog.Create(
                message:        payload.Message,
                stackTrace:     payload.StackTrace,
                innerException: payload.InnerException,
                exceptionType:  payload.ExceptionType,
                requestPath:    payload.RequestPath,
                requestMethod:  payload.RequestMethod,
                userId:         payload.UserId,
                tenantId:       payload.TenantId,
                severity:       payload.Severity);

            // Preserve the ID generated by the originating service for cross-service traceability
            if (payload.Id != Guid.Empty)
                errorLog.Id = payload.Id;

            errorLog.SetHttpDetails(
                statusCode:  payload.StatusCode,
                queryString: payload.QueryString,
                requestBody: payload.RequestBody,
                userAgent:   payload.UserAgent,
                ipAddress:   payload.IpAddress,
                traceId:     payload.TraceId);

            if (!string.IsNullOrWhiteSpace(payload.AdditionalData))
                errorLog.SetAdditionalData(payload.AdditionalData);

            _errorLogRepository.Add(errorLog);
            await _errorLogRepository.SaveChangesAsync(cancellationToken);

            return NoContent();
        }

        /// <summary>Returns all error logs (paginated). Requires user JWT.</summary>
        [HttpGet]
        [Authorize]
        [ProducesResponseType(StatusCodes.Status200OK)]
        public async Task<IActionResult> GetAllErrors(
            [FromQuery] int pageNumber = 1,
            [FromQuery] int pageSize   = 50,
            CancellationToken cancellationToken = default)
        {
            var errors     = await _errorLogRepository.GetAllAsync(pageNumber, pageSize, cancellationToken);
            var totalCount = await _errorLogRepository.GetCountAsync(cancellationToken);

            return Ok(new
            {
                data       = errors,
                pageNumber,
                pageSize,
                totalCount,
                totalPages = (int)Math.Ceiling(totalCount / (double)pageSize)
            });
        }

        /// <summary>Returns all unresolved error logs. Requires user JWT.</summary>
        [HttpGet("unresolved")]
        [Authorize]
        [ProducesResponseType(StatusCodes.Status200OK)]
        public async Task<IActionResult> GetUnresolvedErrors(CancellationToken cancellationToken)
        {
            var errors = await _errorLogRepository.GetUnresolvedAsync(cancellationToken);
            return Ok(errors);
        }

        /// <summary>Returns a single error log by ID. Requires user JWT.</summary>
        [HttpGet("{id:guid}")]
        [Authorize]
        [ProducesResponseType(StatusCodes.Status200OK)]
        [ProducesResponseType(StatusCodes.Status404NotFound)]
        public async Task<IActionResult> GetErrorById(Guid id, CancellationToken cancellationToken)
        {
            var error = await _errorLogRepository.GetByIdAsync(id, cancellationToken);
            if (error is null) return NotFound();
            return Ok(error);
        }

        /// <summary>Marks an error log as resolved. Requires user JWT.</summary>
        [HttpPost("{id:guid}/resolve")]
        [Authorize]
        [ProducesResponseType(StatusCodes.Status200OK)]
        [ProducesResponseType(StatusCodes.Status404NotFound)]
        public async Task<IActionResult> ResolveError(
            Guid id,
            [FromBody] ResolveErrorRequest request,
            CancellationToken cancellationToken)
        {
            var error = await _errorLogRepository.GetByIdAsync(id, cancellationToken);
            if (error is null) return NotFound();

            var userName = User.Identity?.Name ?? "Unknown";
            error.Resolve(userName, request.Notes);

            await _errorLogRepository.SaveChangesAsync(cancellationToken);
            return Ok(new { message = "Error resolved successfully" });
        }
    }

    public sealed record ResolveErrorRequest
    {
        public string? Notes { get; init; }
    }
}